--DDL do in SQL shell
------------------------------------------
drop database if exists "LU.ENGI3675.Proj2";

drop role if exists "LU.ENGI3675";
create role "LU.ENGI3675" login;
comment on role "LU.ENGI3675" is "Restricted IIS app pool user";

drop role if exists "Greg Toombs";
create role "Greg Toombs" login superuser;
comment on role "Greg Toombs" is "Personal developer superuser";

create database "LU.ENGI5675.Proj2";
comment on database "LU.ENGI3675.Proj2" is "Database for ENGI3675 Project 2";

grant connect on database "LU.ENGI3675.Proj2" to "LU.ENGI3675";



----------------------------------------------------------
--SQL do in pgAdmin
----------------------------------------------------------

drop table if exists foods cascade;

create table foods(
	food_id serial primary key, --integer, autoincrement
	name text not null check(length(name)>0),
	quantity int check(quantity >=0)
);

comment on table foods is 'Food products in the store inventory';
comment on column foods.food_id is 'The food autogenerated ID';
comment on column foods.name is 'The name of the food product';
comment on column foods.quantity is 'The quantity of the product in stock.';

grant select, insert, update, delete on table foods to "LU.ENGI3675";


--------------------------
-- Insert SQL in pgAdmin
--------------------------

truncate foods restart identity cascade; --empty the table quickly

insert into foods(name, quantity) values
	('Broccoli', 3),
	('Apple', 10);




